# Generated by Django 4.2.2 on 2023-06-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_marca', models.CharField(max_length=50)),
                ('a_modelo', models.CharField(max_length=50)),
                ('a_year', models.IntegerField()),
                ('a_est', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Motos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_marca', models.CharField(max_length=50)),
                ('m_modelo', models.CharField(max_length=50)),
                ('m_year', models.IntegerField()),
                ('m_est', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_pass', models.CharField(max_length=50)),
                ('user_mail', models.EmailField(max_length=254)),
                ('user_age', models.IntegerField()),
                ('user_est', models.CharField(max_length=10)),
            ],
        ),
    ]
